[package]
name = "cost"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "measure the cost of running your functions"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
cc = "1"